<a href="https://colab.research.google.com/github/DaniBsz/Analisis-exploratorio-de-datos/blob/main/EDA_Parcial_1%20Daniel%20Barragan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
# 1. Importar la libreria y cargar el archivo en un Dataframe llamado "plants"

In [130]:
import pandas as pd
import numpy as np
df = pd.read_csv("plants")

In [131]:
# 2. Cargar las primeras 7 filas

In [132]:
df.head(7)

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
0,Pisum sativum,Pea,Legume,Full sun,Very High,6.0,7.5,Medium,Loamy,Annual,Half hardy,24,4-24,6,55-75,"A good source of vitamin K, manganese, and die...",80.0,Drought intolerant,"The pea is the small spherical seed, or the se...","Require a sunny, nutrient-rich, moisture-reten..."
1,Phaseolus coccineus,Beans (Runner),Legume,Full sun,Medium,6.0,6.8,Medium,Loamy and clay,Annual,Tender,26,16-30,7,65-85,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,Runner bean plants are more productive than gr...,"Beans are a tender, warm-weather crop. They ar..."
2,Phaseolus vulgari,Beans (French),Legume,Full sun,Medium,6.0,7.5,Medium,Any well-drained and fertile,Annual,Tender,26,16-30,7,40-55,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,"French beans are the unripe fruit, and protect...","Beans are a tender, warm-weather crop. They ar..."
3,Vicia faba,Beans (Broad),Legume,Full sun/partial shade/full shade,Very Low,6.0,7.0,Medium,Any well-drained and fertile,Annual,Hardy,10,8-15,7,85-115,"A good source of vitamin-B6 (pyridoxine), thia...",88.0,Drought intolerant,Broad beans - also known as the fava bean - ar...,Broad beans are a cool weather crop. They grow...
4,Brassica oleracea,Cabbage (Spring),Legume,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,55-85,"A very good source of manganese, dietary fibre...",25.0,Particularly vulnerable to pests. Do not grow ...,Cabbages are a leafy green or purple biennial ...,Cabbage is a cool-season crop best planted in ...
5,Brassica oleracea (Italica group),Broccoli,Brassica,Full sun/partial shade,Medium,6.0,7.5,High,Loamy and sandy,NaN,Half hardy,30,7-30,4,55-85,"A good source of vitamin C, folate, dietary fi...",34.0,A cool weather crop best not grown over hot su...,Broccoli is a member of the cabbage family. Th...,"Broccoli grow best in partial-shade, in firm, ..."
6,Brassica oleracea (Gemmifera group),Brussels Sprouts,Brassica,Full sun,Medium,6.0,7.5,High,Loamy,biennial,Hardy,26,7-30,4,180-,"A good source of dietary fibre, vitamin c, and...",35.0,Affected by a wide range of pests and diseases...,Brussels sprouts are a member of the cabbage f...,Brussels sprouts are a cool-season crop. They ...

In [133]:
# 3. Numero de filas y columnas/Numero de filas

In [134]:
df.shape

(140, 20)

In [135]:
'existe bajo la forma de (filas, columnas) o (0, 1)'

'existe bajo la forma de (filas, columnas) o (0, 1)'

In [136]:
df.shape[0]

140

In [137]:
'Hay 140 filas'

'Hay 140 filas'

In [138]:
# 4. Mostrar tipo de dato de la columna energy. Indicar el tipo de dato

In [139]:
df['energy'].dtype

dtype('float64')

In [140]:
 'es un dato tipo float64, lo que significa que es un dato numerico que acepta decimales y la computadora usa 64 bits para guardar ese numero'

'es un dato tipo float64, lo que significa que es un dato numerico que acepta decimales y la computadora usa 64 bits para guardar ese numero'

In [141]:
# 5. Cuántos valores no nulos tiene la columna season. Escribir el codigo y numero

In [142]:
df['season'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 140 entries, 0 to 139
Series name: season
Non-Null Count  Dtype
--------------  -----
67 non-null     object
dtypes: object(1)
memory usage: 1.2+ KB

In [143]:
 'La columna season tiene 67 valores no nulos (67 non-null)'

'La columna season tiene 67 valores no nulos (67 non-null)'

In [144]:
# 6.Extraiga la columna sunlight como Series. Luego extraiga las columnas ['common_name','sunlight','water'] como un nuevo DataFrame llamado sub. Explique en una línea qué diferencia hay entre ambas salidas

In [145]:
# Extraer como serie
serie_sunlight = df['sunlight']

In [146]:
serie_sunlight

0                               Full sun
1                               Full sun
2                               Full sun
3      Full sun/partial shade/full shade
4                               Full sun
                     ...
135                             Full sun
136                             Full sun
137                             Full sun
138                             Full sun
139                             Full sun
Name: sunlight, Length: 140, dtype: object

In [147]:
# Extraer DataFrame
sub = df[['common_name','sunlight','water']]

In [148]:
sub

           common_name                           sunlight      water
0                  Pea                           Full sun  Very High
1       Beans (Runner)                           Full sun     Medium
2       Beans (French)                           Full sun     Medium
3        Beans (Broad)  Full sun/partial shade/full shade   Very Low
4     Cabbage (Spring)                           Full sun       High
..                 ...                                ...        ...
135           Rosemary                           Full sun        Low
136               Sage                           Full sun        Low
137  Tarragon (French)                           Full sun        Low
138         Strawberry                           Full sun     Medium
139         Lemon balm                           Full sun     Medium

[140 rows x 3 columns]

In [149]:
'Al usar un solo corchete con el nombre de una columna se obtiene una Serie (un arreglo unidimensional), mientras que al usar corchetes dobles con una lista de columnas se obtiene un DataFrame (una tabla bidimensional)'

'Al usar un solo corchete con el nombre de una columna se obtiene una Serie (un arreglo unidimensional), mientras que al usar corchetes dobles con una lista de columnas se obtiene un DataFrame (una tabla bidimensional)'

In [150]:
# 7.Usando indexación posicional, extraiga las filas en las posiciones 3 a 8 y las columnas en las posiciones 1 a 3.

In [151]:
df.iloc[3:9, 1:4]

        common_name cultivation                           sunlight
3     Beans (Broad)      Legume  Full sun/partial shade/full shade
4  Cabbage (Spring)      Legume                           Full sun
5          Broccoli    Brassica             Full sun/partial shade
6  Brussels Sprouts    Brassica                           Full sun
7       Cauliflower    Brassica                           Full sun
8              Kale    Brassica                           Full sun

In [152]:
# 8.Usando indexación por etiqueta, extraiga las filas con índice 20 a 24 (ambos incluidos) y las columnas ['common_name', 'nutrients', 'temperature_class]

In [153]:
df.loc[20:24, ['common_name', 'nutrients', 'temperature_class']]

,common_name,nutrients,temperature_class
20,Artichoke (Jerusalem),Low,Very hardy
21,Asparagus,Medium,Hardy
22,Aubergine,High potassium fertiliser every 2 weeks.,Tender
23,Beans (Borlotti),Low,Tender
24,Beetroot,Medium,Half hardy

In [154]:
# 9.Filtre las filas donde cultivation sea exactamente &#39;Legume&#39;. Guarde el resultado en f1 e indique cuántas filas quedan.

In [155]:
f1 = df[df['cultivation'] == 'Legume']

In [156]:
f1

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
0,Pisum sativum,Pea,Legume,Full sun,Very High,6.0,7.5,Medium,Loamy,Annual,Half hardy,24,4-24,6,55-75,"A good source of vitamin K, manganese, and die...",80.0,Drought intolerant,"The pea is the small spherical seed, or the se...","Require a sunny, nutrient-rich, moisture-reten..."
1,Phaseolus coccineus,Beans (Runner),Legume,Full sun,Medium,6.0,6.8,Medium,Loamy and clay,Annual,Tender,26,16-30,7,65-85,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,Runner bean plants are more productive than gr...,"Beans are a tender, warm-weather crop. They ar..."
2,Phaseolus vulgari,Beans (French),Legume,Full sun,Medium,6.0,7.5,Medium,Any well-drained and fertile,Annual,Tender,26,16-30,7,40-55,"A good source of protein, thiamine, and ribofl...",27.0,Drought intolerant,"French beans are the unripe fruit, and protect...","Beans are a tender, warm-weather crop. They ar..."
3,Vicia faba,Beans (Broad),Legume,Full sun/partial shade/full shade,Very Low,6.0,7.0,Medium,Any well-drained and fertile,Annual,Hardy,10,8-15,7,85-115,"A good source of vitamin-B6 (pyridoxine), thia...",88.0,Drought intolerant,Broad beans - also known as the fava bean - ar...,Broad beans are a cool weather crop. They grow...
4,Brassica oleracea,Cabbage (Spring),Legume,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,55-85,"A very good source of manganese, dietary fibre...",25.0,Particularly vulnerable to pests. Do not grow ...,Cabbages are a leafy green or purple biennial ...,Cabbage is a cool-season crop best planted in ...
23,Phaseolus vulgaris,Beans (Borlotti),Legume,Full sun/partial shade,Medium,6.0,6.5,Low,Any well-drained and fertile,NaN,Tender,16,16-30,7,55-80,NaN,NaN,NaN,Pods are picked when mature and then dried.,They are not frost hardy and need sunshine and...
47,Pisum sativum (var. macrocarpon),Mangetout,Legume,Full sun/partial shade,Medium,6.0,7.0,Medium,Loamy,NaN,Half hardy,11,4-24,6,50-170,NaN,NaN,NaN,A flat podded variety of pea eaten whole while...,Require a sunny position with well drained ric...
69,Glycine max,Soybean,Legume,Full sun,Medium,6.0,7.0,Medium,NaN,NaN,Half hardy,24,NaN,NaN,90-100,NaN,NaN,NaN,When to harvest soybean will depend on how you...,Soya is a warm climate plant requiring tempera...
83,Vicia faba,Winter Field Beans,Legume,Full sun,Very low,6.0,7.0,Medium,NaN,NaN,Hardy,10,NaN,NaN,90-180,NaN,NaN,NaN,Winter Beans are an incredibly generous green ...,Sown in autumn they can also limit the effect ...
84,Pisum sativum (subsp. arvense (L.) Asch),Winter Peas,Legume,Full sun,Low,6.0,7.0,Medium,NaN,NaN,Very hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Field peas are an incredibly generous green ma...,Sown in autumn they can also limit the effect ...

In [157]:
f'Quedan {f1.shape[0]} filas'

'Quedan 10 filas'

In [158]:
# 10.Filtre las plantas que cumplan ambas condiciones: sunlight igual a 'Full sun' y nutrients igual a 'Low'. Indicar cuantas filas quedan

In [159]:
f10 = df[(df['sunlight'] == 'Full sun') & (df['nutrients'] == 'Low')]

In [160]:
f10

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
20,Helianthus tuberosus,Artichoke (Jerusalem),Miscellaneous,Full sun,Low,6.5,7.5,Low,Sand/loam/clay,NaN,Very hardy,18-32,18-32,10-17,110-150,NaN,NaN,NaN,This statuesque plant is a relative of the sun...,Jerusalem artichokes are grown from tubers and...
25,Brassica rapa (Chinensis group),Bok Choy,Brassica,Full sun,High,6.5,7.0,Low,Loamy,NaN,Tender,13-24,10-24,6-10,45-60,NaN,NaN,NaN,The stalks are crisp and the leaves are smooth...,"Bok choy can handle full sun, but it grows bes..."
58,Solanum tuberosum,Potatoes (Early),Solanaceae,Full sun,Medium,4.5,6.0,Low,"Well-drained, fertile and high in organic matt...",NaN,Tender,NaN,7-26,NaN,90-115,NaN,NaN,NaN,A versatile tuber which is high in starch and ...,Plant once soil temperatures are above 7°C. Po...
59,Solanum tuberosum,Potatoes (Main crop),Solanaceae,Full sun,Medium,4.5,6.0,Low,"Well-drained, fertile and high in organic matt...",NaN,Tender,NaN,7-26,NaN,100-115,NaN,NaN,NaN,A versatile tuber which is high in starch and ...,Plant once soil temperatures are above 7°C. Po...
61,Chenopodium quinoa,Quinoa,Miscellaneous,Full sun,Low,6.0,7.0,Low,"Well-drained, fertile and loamy",NaN,Tender,18-24,15-20,4,90-120,NaN,NaN,NaN,Mainly grown for it's seeds which are cooked l...,Quinoa is a cool season crop that requires ful...
65,Tragopogon porrifolius,Salsify,Miscellaneous,Full sun,Medium,6.0,7.5,Low,Loamy and sandy,NaN,Half hardy,21,NaN,6,120-,NaN,NaN,NaN,Used in a similar way to other root vegetables...,An easy slow growing cool weather plant that l...
66,Scorzonera hispanica,Scorzonera (Black salsify),Miscellaneous,Full sun,Medium,6.0,7.0,Low,Loamy and sandy,NaN,Hardy,21,NaN,6,120-,NaN,NaN,NaN,Used in a similar way to other root vegetables...,An easy slow growing cool weather plant that l...
67,Allium cepa (var. aggregatum),Shallots,Allium,Full sun,Medium,6.0,7.0,Low,Loamy,NaN,Very hardy,24,NaN,21,90-,NaN,NaN,NaN,"Similar to onions, but are smaller and grow in...",Easy to grow and will do well in any well-drai...
78,Zea mayvar. Saccharata,Sweetcorn,Miscellaneous,Full sun,High,6.0,7.0,Low,Loamy and clay,NaN,Tender,30,16-35,3,70-100,NaN,NaN,NaN,Sweet corn is a variety of maize which is high...,Sweet corn is most successful in long hot summ...
85,Ocimum basilicum,Basil,Lamiaceae,Full sun,high,5.5,6.5,Low,"Loam, Sand",NaN,Very tender,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"A fragrant, easy to grow warm weather leafy he...",For best results plant outside once soil is ov...
86,Laurus nobilis,Bay,Miscellaneous,Full sun,Low,5.5,6.5,Low,"Chalk, Clay, Sand, Loam",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The fragrant leaves of this evergreen tree or ...,An attractive and ornamental plant with fragra...
87,Borago officinalis,Borage,Miscellaneous,Full sun,Medium,5.5,6.5,Low,"Chalk, Clay, Sand, Loam",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A fast growing annual that produces star shape...,An easy to grow annual that will thrive in poo...
93,Rubus fruticosus agg.,Blackberry,Miscellaneous,Full sun,Medium,6.0,7.0,Low,Sandy,Perennial,Very hardy,Not applicable.,NaN,Not applicable.,Not applicable.,NaN,NaN,NaN,"Also known as a bramble, the dark almost black...",Blackberries are vigorous growers and require ...
111,Diospyros chinensis,Persimmon,Miscellaneous,Full sun,Medium,5.5,6.5,Low,NaN,Perennial,Hardy,Not applicable.,NaN,Not applicable.,Not applicable.,NaN,NaN,NaN,Also know as the Sharon fruit. These glossy ye...,"An easy to grow tree that, depending on variet..."
114,Rubus idaeus,Raspberry,Miscellaneous,Full sun,Medium,5.5,6.5,Low,NaN,Perennial,Hardy,Not applicable.,NaN,Not applicable.,Not applicable.,NaN,NaN,NaN,A small soft red fruit containing many seed co...,Most varieties are biennial (fruiting on last ...
121,Nepeta cataria,Catnip,Miscellaneous,Full sun,Low,6.0,7.5,Low,Well drained soil,NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A member of the mint family. Catnip has antiba...,"These seeds are tough, and will need slight da..."
123,Valeriana officinalis,Valerian,Miscellaneous,Full sun,Medium,5.5,7.0,Low,"Sand, Clay, Chalk, Loam",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The root of this plant is used after drying an...,"Will grow in a wide variety of conditions, but..."
125,Coriandrum sativum,Coriander,Umbelliferae,Full sun,Medium,6.0,7.0,Low,"Loam, Chalk, Sand",Annual,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This aromatic herb is used in cooking. The who...,"Keep the soil damp, but not over watered. Dry ..."
127,Thymus vulgaris,Thyme,Miscellaneous,Full sun,Low,5.5,7.0,Low,"Loam, Chalk, Sand",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This is a woody stemmed plant with an abundanc...,"Easy to grow, and suitable for rock gardens. A..."
128,Tanacetum parthenium,Feverfew,Miscellaneous,Full sun,Low,6.0,8.0,Low,Most soils,Annual/perannial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A flowering plant in the daisy family. It is u...,"Will grow well in most soils, but not in heavy..."
130,Cymbopogon citratus,Lemon Grass,Miscellaneous,Full sun,High,5.0,8.0,Low,Loam,NaN,Very tender,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A tall perennial grass used in cooking or infu...,Can be grown from stalk bought for cooking by ...
131,Origanum majorana,Marjoram,Lamiaceae,Full sun,Low,6.0,8.0,Low,"Loam, Chalk, Sand",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A perennial herb grown for it's aromatic flavo...,"Requires regular watering, however, be careful..."
132,Mentha spicata,Mint,Lamiaceae,Full sun,Low,7.0,8.0,Low,"Chalk, Clay, Sand, Loam",Perennial,Very hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A versatile herb which can be used in hot drin...,"An easy to grow herb that will thrive in rich,..."
133,Origanum vulgare,Oregano,Lamiaceae,Full sun,Low,6.0,7.0,Low,"Loam, Chalk, Sand",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A perennial herb grown for it's aromatic flavo...,"Requires regular watering, however, be careful..."
135,Rosmarinus officinalis,Rosemary,Miscellaneous,Full sun,Low,5.0,6.0,Low,"Sand, Clay, Chalk, Loam",Shrub,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"An evergreen shrub, with fragrant needle shape...","An easy to grow shrub that prefers poor, well ..."
136,Salvia officinalis,Sage,Miscellaneous,Full sun,Low,5.5,6.5,Low,"Sand, Chalk, Loam",Perrenial evergreen,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The soft greyish green leaves are traditionall...,An easy herb to grow that does well in most we...
137,Artemisia dracunculus,Tarragon (French),Miscellaneous,Full sun,Low,6.5,7.5,Low,"Loam, Sand",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tarragon is reported to be one of the top 4 he...,"Does not set viable seed, so buying young plan..."

In [161]:
f'Quedan {f10.shape[0]} filas'

'Quedan 27 filas'

In [162]:
# 11.Filtre las plantas cuyo preferred_ph_upper sea >= 7.5 y muestre solo las columnas common_name y preferred_ph_upper. Indique cuántas filas cumplen

In [165]:
f11 = df.loc[df['preferred_ph_upper'] >= 7.5, ['common_name', 'preferred_ph_upper']]

In [167]:
f11

                      common_name  preferred_ph_upper
0                             Pea                 7.5
2                  Beans (French)                 7.5
4                Cabbage (Spring)                 7.5
5                        Broccoli                 7.5
6                Brussels Sprouts                 7.5
7                     Cauliflower                 7.5
8                            Kale                 7.5
9                          Turnip                 7.5
12                          Melon                 7.5
20          Artichoke (Jerusalem)                 7.5
21                      Asparagus                 7.5
24                       Beetroot                 7.5
26           Cabbage (Autumn red)                 7.5
27               Cabbage (Autumn)                 7.5
28              Cabbage (Chinese)                 7.5
29           Cabbage (Spring red)                 7.5
30           Cabbage (Summer red)                 7.5
31               Cabbage (Summer)                 7.5
35                  Chilli Pepper                 8.5
36                         Chives                 7.5
40                         Garlic                 7.5
42                       Kohlrabi                 7.5
43                           Leek                 7.5
48                         Marrow                 7.5
50                        Mustard                 7.5
51                           Okra                 7.5
56                        Parsnip                 7.5
65                        Salsify                 7.5
70                        Spinach                 7.5
79                    Swiss Chard                 7.5
80                         Tatsoi                 7.5
81                Tomato (Cherry)                 7.5
82               Tomato (Regular)                 7.5
88                  Bonnet Pepper                 8.5
89   Chamomile (German chamomile)                 7.5
91                          Apple                 7.5
92                        Apricot                 8.0
101                         Hazel                 7.5
102                          Hops                 8.0
112                          Plum                 8.0
116                        Walnut                 7.5
121                        Catnip                 7.5
122   Chamomile (Roman chamomile)                 7.5
128                      Feverfew                 8.0
129                   Horseradish                 7.5
130                   Lemon Grass                 8.0
131                      Marjoram                 8.0
132                          Mint                 8.0
137             Tarragon (French)                 7.5
139                    Lemon balm                 7.5

In [166]:
f'Cumplen {f11.shape[0]} filas'

'Cumplen 50 filas'

In [172]:
# 12. Sin usar el operador |, filtre las filas cuyo temperature_class esté entre ['Tender', 'Very_tender] y muestre solo las columnas ['common_name', 'temperature_class']

In [169]:
f12 = df.loc[df['temperature_class'].isin(['Tender', 'Very tender']), ['common_name', 'temperature_class']]

In [170]:
f12

                    common_name temperature_class
1                Beans (Runner)            Tender
2                Beans (French)            Tender
10        Zucchini or Courgette            Tender
11                     Cucumber            Tender
12                        Melon            Tender
14                  Water melon            Tender
15             Lettuce (Headed)            Tender
16                       Celery            Tender
18             Amaranth (Grain)            Tender
19            Artichoke (Globe)            Tender
22                    Aubergine            Tender
23             Beans (Borlotti)            Tender
25                     Bok Choy            Tender
28            Cabbage (Chinese)            Tender
32                    Calabrese            Tender
35                Chilli Pepper            Tender
37                        Cress            Tender
41                       Ginger            Tender
44   Lettuce (Lambs/Corn Salad)            Tender
45         Lettuce (Loose Leaf)            Tender
48                       Marrow            Tender
51                         Okra            Tender
57                  Bell Pepper            Tender
58             Potatoes (Early)            Tender
59         Potatoes (Main crop)            Tender
61                       Quinoa            Tender
71        Spinach (New Zealand)            Tender
74              Squash (Summer)            Tender
75              Squash (Winter)            Tender
78                    Sweetcorn            Tender
81              Tomato (Cherry)            Tender
82             Tomato (Regular)            Tender
85                        Basil       Very tender
88                Bonnet Pepper            Tender
90                       Almond            Tender
104                       Lemon            Tender
105                        Lime            Tender
108                      Orange            Tender
130                 Lemon Grass       Very tender

In [171]:
f'Cumplen {f12.shape[0]} filas'

'Cumplen 39 filas'

In [174]:
# 13.Filtre las filas cuyo common_name contenga el texto 'cabbage', sin distinguir mayúsculas de minúsculas y sin que los valores faltantes generen error. Indique cuántas filas cumplen.

In [175]:
f13 = df[df['common_name'].str.contains('cabbage', case=False, na=False)]

In [176]:
f13

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
4,Brassica oleracea,Cabbage (Spring),Legume,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,55-85,"A very good source of manganese, dietary fibre...",25.0,Particularly vulnerable to pests. Do not grow ...,Cabbages are a leafy green or purple biennial ...,Cabbage is a cool-season crop best planted in ...
26,Brassica oleracea,Cabbage (Autumn red),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
27,Brassica oleracea,Cabbage (Autumn),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
28,Brassica rapa (Chinensis group),Cabbage (Chinese),Brassica,Full sun,High,6.0,7.5,High,Loamy,NaN,Tender,13-24,10-24,6-10,45-60,NaN,NaN,NaN,Also know as napa cabbage and is a close relat...,"Chinese cabbage can handle full sun, but it gr..."
29,Brassica oleracea,Cabbage (Spring red),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
30,Brassica oleracea,Cabbage (Summer red),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
31,Brassica oleracea,Cabbage (Summer),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...

In [177]:
f'Cumplen {f13.shape[0]} filas'

'Cumplen 7 filas'

In [178]:
# 14.Filtre las filas donde water no sea 'Medium', usando el operador de negación ~. Indique cuántas filas quedan y verifique que la suma con su complemento da el total.

In [186]:
f14 = df[~ (df['water'] == 'Medium')]

In [187]:
f14

,taxonomic_name,common_name,cultivation,sunlight,water,preferred_ph_lower,preferred_ph_upper,nutrients,soil,season,temperature_class,temperature_germination,temperature_growing,days_germination,days_harvest,nutritional_info,energy,sensitivities,description,requirements
0,Pisum sativum,Pea,Legume,Full sun,Very High,6.0,7.5,Medium,Loamy,Annual,Half hardy,24,4-24,6,55-75,"A good source of vitamin K, manganese, and die...",80.0,Drought intolerant,"The pea is the small spherical seed, or the se...","Require a sunny, nutrient-rich, moisture-reten..."
3,Vicia faba,Beans (Broad),Legume,Full sun/partial shade/full shade,Very Low,6.0,7.0,Medium,Any well-drained and fertile,Annual,Hardy,10,8-15,7,85-115,"A good source of vitamin-B6 (pyridoxine), thia...",88.0,Drought intolerant,Broad beans - also known as the fava bean - ar...,Broad beans are a cool weather crop. They grow...
4,Brassica oleracea,Cabbage (Spring),Legume,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,55-85,"A very good source of manganese, dietary fibre...",25.0,Particularly vulnerable to pests. Do not grow ...,Cabbages are a leafy green or purple biennial ...,Cabbage is a cool-season crop best planted in ...
8,Brassica oleracea (Acephala group),Kale,Brassica,Full sun,Low,6.0,7.5,High,Loamy,"biennial, grown as annual",Very hardy,26,15-20,4,65-75,"A good source of vitamin A, vitamin C, calcium...",50.0,Heat intolerant,"Kale is a variety of the common cabbage, howev...",Kale tolerates cold weather better than most o...
11,Cucumis sativus,Cucumber,Cucurbit,Full sun/partial shade,High,5.5,7.0,High,Any well-drained and fertile,Annual,Tender,35,16-35,3,90-120,NaN,NaN,NaN,A climbing plant that produces fruits that are...,There are indoor and outdoor varieties availab...
12,Cucumis melo,Melon,Cucurbit,Full sun,High,5.5,7.5,High,Loamy,Annual,Tender,24-32,18-,4-10,75-100,NaN,NaN,NaN,A sweet fruit eaten raw with a high water cont...,"Melons are tender plants. They need a warm, an..."
14,Citrullus lanatus,Water melon,Cucurbit,Full sun,High,6.0,7.0,High,Sandy,Annual,Tender,35,26,4,80-100,NaN,NaN,NaN,The flesh of these large fruits are eaten raw....,"Native to Africa, melons are very tender and n..."
15,Lactuca sativa,Lettuce (Headed),Salad,Partial shade,High,6.0,7.0,Medium,Any well-drained and fertile,Annual,Tender,24,4-27,3,45-100,NaN,NaN,NaN,Hearting lettuces have a dense centre of leave...,Lettuce requires full sun on moisture-retentiv...
16,Apium graveolens,Celery,Salad,Full sun/partial shade,High,6.0,7.0,High,Loamy,NaN,Tender,21,13-,7,90-140,NaN,NaN,NaN,The leaves and stems of this plant are eaten e...,Celery is a long-season crop that can be trick...
17,cichorium intybus,Chicory,Salad,Full sun/partial shade,Low,6.0,6.7,Low,"Chalky, sandy and clay",NaN,Hardy,21,10-25,6,75-80,NaN,NaN,NaN,The leaves are eaten raw or cooked and are oft...,"Chicory prefers an open, sunny site, with mode..."
20,Helianthus tuberosus,Artichoke (Jerusalem),Miscellaneous,Full sun,Low,6.5,7.5,Low,Sand/loam/clay,NaN,Very hardy,18-32,18-32,10-17,110-150,NaN,NaN,NaN,This statuesque plant is a relative of the sun...,Jerusalem artichokes are grown from tubers and...
22,Solanum melongena,Aubergine,Solanaceae,Full sun,very high,5.5,7.0,High potassium fertiliser every 2 weeks.,Loamy and potting mix,NaN,Tender,30,24-32,4,65-80,NaN,NaN,NaN,"Grown for it's egg-shaped, glossy, purple frui...",Sunshine and warm growing conditions are the k...
25,Brassica rapa (Chinensis group),Bok Choy,Brassica,Full sun,High,6.5,7.0,Low,Loamy,NaN,Tender,13-24,10-24,6-10,45-60,NaN,NaN,NaN,The stalks are crisp and the leaves are smooth...,"Bok choy can handle full sun, but it grows bes..."
26,Brassica oleracea,Cabbage (Autumn red),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
27,Brassica oleracea,Cabbage (Autumn),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
28,Brassica rapa (Chinensis group),Cabbage (Chinese),Brassica,Full sun,High,6.0,7.5,High,Loamy,NaN,Tender,13-24,10-24,6-10,45-60,NaN,NaN,NaN,Also know as napa cabbage and is a close relat...,"Chinese cabbage can handle full sun, but it gr..."
29,Brassica oleracea,Cabbage (Spring red),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
30,Brassica oleracea,Cabbage (Summer red),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
31,Brassica oleracea,Cabbage (Summer),Brassica,Full sun,High,6.0,7.5,High,Sand/loam/clay,biennial,Hardy,26,7-30,4,60-110,NaN,NaN,NaN,"Also known as headed cabbage, grown for it's t...",Cabbage is a cool-season crop best planted in ...
33,Daucus carota,Carrot,Umbelliferae,Full sun/partial shade,High,5.5,7.0,Low,Loamy and sandy,biennial,Hardy,26,7-30,4,60-80,NaN,NaN,NaN,The swollen taproot of this fast growing plant...,"Best grown in light, fertile soil in a sunny p..."
34,Apium graveolens (var. rapaceum),Celeriac,Umbelliferae,Full sun,High,5.5,6.5,Medium,NaN,NaN,Hardy,21-24,15-18,11,90-120,NaN,NaN,NaN,Also called turnip-rooted celery. The whole pl...,Celeriac is hardier and more disease resistant...
41,Zingiber officinale,Ginger,Miscellaneous,Partial shade,High,5.0,6.0,Medium,NaN,NaN,Tender,NaN,NaN,NaN,240-,NaN,NaN,NaN,This flowering plant is a herbaceous perennial...,"In warm climates it can be grown outdoors, cho..."
44,Valerianella locusta,Lettuce (Lambs/Corn Salad),Miscellaneous,Full sun,High,6.0,7.0,Medium,Loamy,NaN,Tender,13,4-27,7,30-60,NaN,NaN,NaN,A small annual plant who’s leaves are eaten ra...,Corn salad grows best on fertilizer remaining ...
45,Lactuca sativa,Lettuce (Loose Leaf),Miscellaneous,Partial shade,High,6.0,7.0,Medium,Loamy,NaN,Tender,24,4-27,NaN,60-,NaN,NaN,NaN,The crisp leaves of lettuce are used in salads...,Grow lettuces in full sun on moisture-retentiv...
46,Claytonia perfoliata,Winter Purslane (Miners lettuce),Miscellaneous,Full sun/partial shade,High,6.0,7.0,Medium,NaN,NaN,Very hardy,10,4-27,NaN,60-,NaN,NaN,NaN,These succulent and juicy leaves are on of the...,"Plants do best in a slightly shaded position, ..."
49,Brassica juncea (var. japonica),Mizuna,Brassica,Full sun/partial shade,High,6.5,7.0,High,NaN,NaN,Hardy,NaN,NaN,NaN,21-50,NaN,NaN,NaN,A finely desiccated leaf with a peppery flavou...,"Prefer to be grown on rich, loamy soils with h..."
51,Abelmoschus esculentus,Okra,Miscellaneous,Full sun,High,6.0,7.5,Medium,Loamy,NaN,Tender,35,NaN,6,50-60,NaN,NaN,NaN,"A tapering seed pod which produces a sticky, v...",Okra likes well drained soil warm weather and ...
60,Portulaca oleracea,Purslane,Miscellaneous,Full sun/partial shade,Low,5.5,7.0,Low,"Loamy, sandy and silty",NaN,Hardy,32,NaN,NaN,40-100,NaN,NaN,NaN,Purslane is an annual succulent that is eaten ...,Purslane is a fast-growing annual with succule...
61,Chenopodium quinoa,Quinoa,Miscellaneous,Full sun,Low,6.0,7.0,Low,"Well-drained, fertile and loamy",NaN,Tender,18-24,15-20,4,90-120,NaN,NaN,NaN,Mainly grown for it's seeds which are cooked l...,Quinoa is a cool season crop that requires ful...
78,Zea mayvar. Saccharata,Sweetcorn,Miscellaneous,Full sun,High,6.0,7.0,Low,Loamy and clay,NaN,Tender,30,16-35,3,70-100,NaN,NaN,NaN,Sweet corn is a variety of maize which is high...,Sweet corn is most successful in long hot summ...
83,Vicia faba,Winter Field Beans,Legume,Full sun,Very low,6.0,7.0,Medium,NaN,NaN,Hardy,10,NaN,NaN,90-180,NaN,NaN,NaN,Winter Beans are an incredibly generous green ...,Sown in autumn they can also limit the effect ...
84,Pisum sativum (subsp. arvense (L.) Asch),Winter Peas,Legume,Full sun,Low,6.0,7.0,Medium,NaN,NaN,Very hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Field peas are an incredibly generous green ma...,Sown in autumn they can also limit the effect ...
85,Ocimum basilicum,Basil,Lamiaceae,Full sun,high,5.5,6.5,Low,"Loam, Sand",NaN,Very tender,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"A fragrant, easy to grow warm weather leafy he...",For best results plant outside once soil is ov...
86,Laurus nobilis,Bay,Miscellaneous,Full sun,Low,5.5,6.5,Low,"Chalk, Clay, Sand, Loam",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The fragrant leaves of this evergreen tree or ...,An attractive and ornamental plant with fragra...
89,Matricaria recutita,Chamomile (German chamomile),Miscellaneous,Full sun/partial shade,Low,5.5,7.5,low,"Loam, Chalk, Sand",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The dried flowers of the chamomile plant conta...,This upright annual grows best in partial shad...
97,Vaccinium corymbosum,Cranberry,Miscellaneous,Full sun/partial shade,High,5.0,6.0,Medium,NaN,Perennial,Hardy,Not applicable.,NaN,Not applicable.,Not applicable.,NaN,NaN,NaN,"These evergreen dwarf shrubs, or trailing vine...","Requires a soil pH of 5.5 or lower to thrive, ..."
121,Nepeta cataria,Catnip,Miscellaneous,Full sun,Low,6.0,7.5,Low,Well drained soil,NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A member of the mint family. Catnip has antiba...,"These seeds are tough, and will need slight da..."
122,Chamaemelum nobile,Chamomile (Roman chamomile),Miscellaneous,Full sun/partial shade,Low,5.5,7.5,Low,"Loam, Chalk, Sand",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The dried flowers of the chamomile plant conta...,"A creeping, ground covering perennial. It grow..."
127,Thymus vulgaris,Thyme,Miscellaneous,Full sun,Low,5.5,7.0,Low,"Loam, Chalk, Sand",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,This is a woody stemmed plant with an abundanc...,"Easy to grow, and suitable for rock gardens. A..."
128,Tanacetum parthenium,Feverfew,Miscellaneous,Full sun,Low,6.0,8.0,Low,Most soils,Annual/perannial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A flowering plant in the daisy family. It is u...,"Will grow well in most soils, but not in heavy..."
130,Cymbopogon citratus,Lemon Grass,Miscellaneous,Full sun,High,5.0,8.0,Low,Loam,NaN,Very tender,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A tall perennial grass used in cooking or infu...,Can be grown from stalk bought for cooking by ...
131,Origanum majorana,Marjoram,Lamiaceae,Full sun,Low,6.0,8.0,Low,"Loam, Chalk, Sand",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A perennial herb grown for it's aromatic flavo...,"Requires regular watering, however, be careful..."
132,Mentha spicata,Mint,Lamiaceae,Full sun,Low,7.0,8.0,Low,"Chalk, Clay, Sand, Loam",Perennial,Very hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A versatile herb which can be used in hot drin...,"An easy to grow herb that will thrive in rich,..."
133,Origanum vulgare,Oregano,Lamiaceae,Full sun,Low,6.0,7.0,Low,"Loam, Chalk, Sand",NaN,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A perennial herb grown for it's aromatic flavo...,"Requires regular watering, however, be careful..."
135,Rosmarinus officinalis,Rosemary,Miscellaneous,Full sun,Low,5.0,6.0,Low,"Sand, Clay, Chalk, Loam",Shrub,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"An evergreen shrub, with fragrant needle shape...","An easy to grow shrub that prefers poor, well ..."
136,Salvia officinalis,Sage,Miscellaneous,Full sun,Low,5.5,6.5,Low,"Sand, Chalk, Loam",Perrenial evergreen,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The soft greyish green leaves are traditionall...,An easy herb to grow that does well in most we...
137,Artemisia dracunculus,Tarragon (French),Miscellaneous,Full sun,Low,6.5,7.5,Low,"Loam, Sand",Perennial,Hardy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tarragon is reported to be one of the top 4 he...,"Does not set viable seed, so buying young plan..."

In [190]:
f'Quedan {f14.shape[0]} filas'

'Quedan 47 filas'

In [191]:
complemento = df[df['water'] == 'Medium']
total_suma = f14.shape[0] + complemento.shape[0]
total_original = df.shape[0]

In [192]:
f'Suma de filtro + complemento: {total_suma}'

'Suma de filtro + complemento: 140'

In [193]:
f'Total del DataFrame original: {total_original}'

'Total del DataFrame original: 140'