<a href="https://colab.research.google.com/github/DaniBsz/Analisis-exploratorio-de-datos/blob/main/factbookDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
file = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2024/2024-10-22/cia_factbook.csv"

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2024/2024-10-22/cia_factbook.csv')

In [4]:
df

,country,area,birth_rate,death_rate,infant_mortality_rate,internet_users,life_exp_at_birth,maternal_mortality_rate,net_migration_rate,population,population_growth_rate
0,Russia,17098242.0,11.87,13.83,7.08,40853000.0,70.16,34.0,1.69,1.424703e+08,-0.03
1,Canada,9984670.0,10.29,8.31,4.71,26960000.0,81.67,12.0,5.66,3.483484e+07,0.76
2,United States,9826675.0,13.42,8.15,6.17,245000000.0,79.56,21.0,2.45,3.188921e+08,0.77
3,China,9596960.0,12.17,7.44,14.79,389000000.0,75.15,37.0,-0.32,1.355693e+09,0.44
4,Brazil,8514877.0,14.72,6.54,19.21,75982000.0,73.28,56.0,-0.15,2.026568e+08,0.80
...,...,...,...,...,...,...,...,...,...,...,...
254,Bouvet Island,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Palmyra Atoll,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
256,Akrotiri,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,European Union,NaN,NaN,NaN,4.33,NaN,80.02,NaN,NaN,5.114348e+08,NaN
258,Saint Barthelemy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.267000e+03,NaN

In [5]:
print(50*'#')
print(df)

print(df.describe)

##################################################
              country        area  birth_rate  death_rate  \
0              Russia  17098242.0       11.87       13.83
1              Canada   9984670.0       10.29        8.31
2       United States   9826675.0       13.42        8.15
3               China   9596960.0       12.17        7.44
4              Brazil   8514877.0       14.72        6.54
..                ...         ...         ...         ...
254     Bouvet Island        49.0         NaN         NaN
255     Palmyra Atoll        12.0         NaN         NaN
256          Akrotiri       123.0         NaN         NaN
257    European Union         NaN         NaN         NaN
258  Saint Barthelemy         NaN         NaN         NaN

     infant_mortality_rate  internet_users  life_exp_at_birth  \
0                     7.08      40853000.0              70.16
1                     4.71      26960000.0              81.67
2                     6.17     245000000.0              79.56
3                    14.79     389000000.0              75.15
4                    19.21      75982000.0              73.28
..                     ...             ...                ...
254                    NaN             NaN                NaN
255                    NaN             NaN                NaN
256                    NaN             NaN                NaN
257                   4.33             NaN              80.02
258                    NaN             NaN                NaN

     maternal_mortality_rate  net_migration_rate    population  \
0                       34.0                1.69  1.424703e+08
1                       12.0                5.66  3.483484e+07
2                       21.0                2.45  3.188921e+08
3                       37.0               -0.32  1.355693e+09
4                       56.0               -0.15  2.026568e+08
..                       ...                 ...           ...
254                      NaN                 NaN           NaN
255                      NaN                 NaN           NaN
256                      NaN                 NaN           NaN
257                      NaN                 NaN  5.114348e+08
258                      NaN                 NaN  7.267000e+03

     population_growth_rate
0                     -0.03
1                      0.76
2                      0.77
3                      0.44
4                      0.80
..                      ...
254                     NaN
255                     NaN
256                     NaN
257                     NaN
258                     NaN

[259 rows x 11 columns]
<bound method NDFrame.describe of               country        area  birth_rate  death_rate  \
0              Russia  17098242.0       11.87       13.83
1              Canada   9984670.0       10.29        8.31
2       United States   9826675.0       13.42        8.15
3               China   9596960.0       12.17        7.44
4              Brazil   8514877.0       14.72        6.54
..                ...         ...         ...         ...
254     Bouvet Island        49.0         NaN         NaN
255     Palmyra Atoll        12.0         NaN         NaN
256          Akrotiri       123.0         NaN         NaN
257    European Union         NaN         NaN         NaN
258  Saint Barthelemy         NaN         NaN         NaN

     infant_mortality_rate  internet_users  life_exp_at_birth  \
0                     7.08      40853000.0              70.16
1                     4.71      26960000.0              81.67
2                     6.17     245000000.0              79.56
3                    14.79     389000000.0              75.15
4                    19.21      75982000.0              73.28
..                     ...             ...                ...
254                    NaN             NaN                NaN
255                    NaN             NaN                NaN
256                    NaN             NaN                NaN
257                   4.33             NaN              80.02
258                    NaN             NaN                NaN

     maternal_mortality_rate  net_migration_rate    population  \
0                       34.0                1.69  1.424703e+08
1                       12.0                5.66  3.483484e+07
2                       21.0                2.45  3.188921e+08
3                       37.0               -0.32  1.355693e+09
4                       56.0               -0.15  2.026568e+08
..                       ...                 ...           ...
254                      NaN                 NaN           NaN
255                      NaN                 NaN           NaN
256                      NaN                 NaN           NaN
257                      NaN                 NaN  5.114348e+08
258                      NaN                 NaN  7.267000e+03

     population_growth_rate
0                     -0.03
1                      0.76
2                      0.77
3                      0.44
4                      0.80
..                      ...
254                     NaN
255                     NaN
256                     NaN
257                     NaN
258                     NaN

[259 rows x 11 columns]>

In [6]:
print(df.shape)

(259, 11)

In [7]:
print(df.shape[1])
print(df.shape[0])

11
259

In [8]:
print(f'la df se compone de', df.shape[1], 'columnas')
print('y')
print(f'la df se compone de', df.shape[0], 'filas')

la df se compone de 11 columnas
y
la df se compone de 259 filas

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259 entries, 0 to 258
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  259 non-null    object
 1   area                     257 non-null    float64
 2   birth_rate               224 non-null    float64
 3   death_rate               225 non-null    float64
 4   infant_mortality_rate    224 non-null    float64
 5   internet_users           213 non-null    float64
 6   life_exp_at_birth        224 non-null    float64
 7   maternal_mortality_rate  184 non-null    float64
 8   net_migration_rate       222 non-null    float64
 9   population               238 non-null    float64
 10  population_growth_rate   233 non-null    float64
dtypes: float64(10), object(1)
memory usage: 22.4+ KB

In [10]:
df.describe()

,area,birth_rate,death_rate,infant_mortality_rate,internet_users,life_exp_at_birth,maternal_mortality_rate,net_migration_rate,population,population_growth_rate
count,2.570000e+02,224.000000,225.000000,224.000000,2.130000e+02,224.000000,184.000000,222.000000,2.380000e+02,233.000000
mean,5.308881e+05,19.659063,7.906978,24.484420,8.311771e+06,71.826875,177.972826,-0.181577,3.229436e+07,1.100858
std,1.696869e+06,9.669575,2.979933,24.077809,3.350725e+07,8.798460,262.508297,11.142682,1.277013e+08,1.418633
min,0.000000e+00,6.720000,1.530000,1.810000,4.640000e+02,49.440000,2.000000,-113.510000,4.800000e+01,-9.730000
25%,6.160000e+02,11.840000,5.930000,6.185000,8.640000e+04,67.000000,20.000000,-2.015000,3.265865e+05,0.260000
50%,5.119700e+04,16.890000,7.630000,13.985000,7.164000e+05,74.360000,65.500000,-0.045000,5.220371e+06,1.020000
75%,3.381450e+05,24.915000,9.450000,38.655000,4.200000e+06,78.292500,240.000000,1.257500,1.826175e+07,1.920000
max,1.709824e+07,46.120000,17.490000,117.230000,3.890000e+08,89.570000,2054.000000,83.820000,1.355693e+09,9.370000

In [11]:
maxima_area= df['area']

In [12]:
maxima_area

0      17098242.0
1       9984670.0
2       9826675.0
3       9596960.0
4       8514877.0
          ...
254          49.0
255          12.0
256         123.0
257           NaN
258           NaN
Name: area, Length: 259, dtype: float64

In [13]:
df[df['internet_users']==df['internet_users'].min()]['country']

217    Christmas Island
Name: country, dtype: object

In [14]:
print(2 == 2)
print(2 != 2)
print(3 <= 4)

True
False
True

In [15]:
df[(df['death_rate']==df['death_rate'].max()) & (df['maternal_mortality_rate'] == df['maternal_mortality_rate'].max())]['country']

Series([], Name: country, dtype: object)

In [16]:
print(f'Hay', df[df['death_rate'] > 9.45].shape[0], 'paises con la mayor mortalidad infantil')

Hay 56 paises con la mayor mortalidad infantil

In [17]:
df['death_rate'] > 9.45

0       True
1      False
2      False
3      False
4      False
       ...
254    False
255    False
256    False
257    False
258    False
Name: death_rate, Length: 259, dtype: bool

In [18]:
filtro2 = df.death_rate.between(5.93, 7.63)

In [19]:
df[filtro2].shape[0]

58

In [20]:
df['population']

0      1.424703e+08
1      3.483484e+07
2      3.188921e+08
3      1.355693e+09
4      2.026568e+08
           ...
254             NaN
255             NaN
256             NaN
257    5.114348e+08
258    7.267000e+03
Name: population, Length: 259, dtype: float64

In [21]:
#Calculo de la densidad poblacional
df['density'] = df['population'] / df['area']

In [22]:
df['density']

0        8.332451
1        3.488832
2       32.451679
3      141.262710
4       23.800319
          ...
254           NaN
255           NaN
256           NaN
257           NaN
258           NaN
Name: density, Length: 259, dtype: float64

In [23]:
#Calculo de la densidad de usuarios de internet
df['IntuDensity']= df['internet_users'] / df['population']

In [24]:
df[df['IntuDensity'] == df['IntuDensity'].max()]['country']

107    Iceland
Name: country, dtype: object

In [29]:
df['internet_users_per_sqkm'] = df['internet_users'] / df['area']
print(f"País con la mayor cantidad de usuarios de internet por kilómetro cuadrado: {df[df['internet_users_per_sqkm'] == df['internet_users_per_sqkm'].max()]['country'].iloc[0]}")

País con la mayor cantidad de usuarios de internet por kilómetro cuadrado: Monaco

In [26]:
df['percentage_internet_users'] = (df['internet_users'] / df['population']) * 100
print(f"País con el mayor porcentaje de usuarios de internet: {df[df['percentage_internet_users'] == df['percentage_internet_users'].max()]['country'].iloc[0]}")

País con el mayor porcentaje de usuarios de internet: Iceland